### ISSUE TITLE
Auto add metabox to post types that support comments

### ISSUE THREAD

**Issue by pippinsplugins** [norcross/wp-comment-notes#1]
Instead of just adding the meta box to the `post` post type, how about we auto add it to all plugins that support `comments` and that are public.

Thoughts?

**Comment by norcross** [comment]
(I assume you mean post types that support).

I thought that, but here was my thinking: pages support comments by default, but 99% of people have them disabled. so they'd get the metaboxes for no reason.

**Comment by pippinsplugins** [comment]
lol, yes, I meant post types that support comments.

That's true about pages. Hmm, we can leave as a filter for now and see if we get requests for it.

**Comment by norcross** [comment]
makes sense. I may do something about CPTs.

**Comment by pippinsplugins** [comment]
How about we do what I suggested above but also add on to it a little. We can easily check if the item being edited (of a post type that supports comments) has comments allowed. If comments are allowed, show the meta box, otherwise hide it.

**Comment by norcross** [comment]
I'm good either way. I was working on something to do a post_type_supports check, but it was tricky to get it to match the wp_enqueue_scripts call as well

**Comment by pippinsplugins** [comment]
Working on a pull request now.

**Comment by norcross** [comment]
merged the pull request
